### ISSUE TITLE
Detect when service is not running

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#132]
```
If the service is not running, show a message to the user letting them know.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 13 Aug 2014 at 4:19

**Comment by canadainc** [comment]
8baa8c8ed0f2e632afe02d07b2f70780c59258c3

**Comment by canadainc** [comment]
4d43ff8c6e116e8153c82009c700c5854da42f0a
