### ISSUE TITLE
If athan tries go off during phone call the volume down key does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#147]
```
1. Be on a phone call
2. Let athan go off.
3. Press vol down key it won't work anymore.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 12 Oct 2014 at 5:22

**Comment by canadainc** [comment]
85d821d76767d4e8e0c9a07173ae5dcf005a1665

**Comment by canadainc** [comment]
canadainclib: bec577d1c674ed6df277d21deba442d609bf906b
