### ISSUE TITLE
Times in India seem to be incorrect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#148]
```
http://islamicfinder.org/prayerDetail.php?latitude=12.7686756&longitude=75.20706
44&timezone=5.5&pmethod=3&fajrTwilight1=10&ishaTwilight=10&fajrTwilight2=10&isha
Interval=30&HanfiShafi=1&dhuhrInterval=1&maghribInterval=1&id=35478&daylight=0&p
rayerCustomize=1&city=puttur&state=&state_name=Karnataka&zipcode=&country=india&
day=13&month=10&year=2014&athan=&aversion=&lang=
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 18 Oct 2014 at 1:27

**Comment by canadainc** [comment]
http://www.islamicfinder.org/prayerDetail.php?latitude=12.7686756&longitude=75.2070644&timezone=5.5&pmethod=3&fajrTwilight1=18&ishaTwilight=10&fajrTwilight2=18&ishaInterval=30&HanfiShafi=1&dhuhrInterval=1&maghribInterval=1&id=25926&daylight=0&prayerCustomize=1&city=puttur&state=41&state_name=Karnataka&zipcode=&country=india&day=12&month=10&year=2014&athan=&aversion=&lang=

=== ../src/Persistance.cpp 181 getValueFor "adjustments" QVariant(QVariantMap, QMap(("asr", QVariant(int, 0) ) ( "dhuhr" ,  QVariant(int, 0) ) ( "fajr" ,  QVariant(int, 0) ) ( "halfNight" ,  QVariant(int, 0) ) ( "isha" ,  QVariant(int, 0) ) ( "lastThirdNight" ,  QVariant(int, 9) ) ( "maghrib" ,  QVariant(int, 0) ) ( "sunrise" ,  QVariant(int, 0) ) )  ) 

=== ../src/DataModelWrapper.cpp 48 calculate (QDateTime("Sun Oct 12 04:33:01 2014") ,  QDateTime("Sun Oct 12 05:49:53 2014") ,  QDateTime("Sun Oct 12 11:48:02 2014") ,  QDateTime("Sun Oct 12 15:08:52 2014") ,  QDateTime("Sun Oct 12 17:44:13 2014") ,  QDateTime("Sun Oct 12 18:53:50 2014") ,  QDateTime("Sun Oct 12 23:08:37 2014") ,  QDateTime("Mon Oct 13 00:56:45 2014") )  

latitude=12.7686756
longitude=75.2070644
location="Puttur, Karnataka, India"



1435 12 18 
, 
2014 - 10 - 12 
, 
5 
: 
0 
9 
, 
6 
: 
19 
, 
12 
: 
17 
, 
15 
: 
38 
, 
18 
: 
14 
, 
19 
: 
25 

 
=== ../src/applicationui.cpp 137 lazyInit (QDateTime("Sun Oct 12 05:09:11 2014") ,  QDateTime("Sun Oct 12 06:19:53 2014") ,  QDateTime("Sun Oct 12 12:18:02 2014") ,  QDateTime("Sun Oct 12 15:38:52 2014") ,  QDateTime("Sun Oct 12 18:14:13 2014") ,  QDateTime("Sun Oct 12 19:25:53 2014") ,  QDateTime("Sun Oct 12 23:41:42 2014") ,  QDateTime("Mon Oct 13 01:30:51 2014") )

**Comment by canadainc** [comment]
4:33 instead of 5:09. Why the difference?

Seems like settings file Muhammad Ashiq: 1413225737911
it showing angles are set to EGAS but strategy is set to UISK...

**Comment by canadainc** [comment]
actually:

=== ../src/Persistance.cpp 197 saveValueFor "strategy" QVariant(QString, "uisk") 
=== ../src/Persistance.cpp 197 saveValueFor "angles" QVariant(QVariantMap, QMap(("dhuhrInterval", QVariant(int, 1) ) ( "fajrTwilightAngle" ,  QVariant(int, 18) ) ( "ishaInterval" ,  QVariant(int, 0) ) ( "ishaTwilightAngle" ,  QVariant(int, 18) ) ( "maghribInterval" ,  QVariant(int, 1) ) )  ) 
=== ../src/Persistance.cpp 181 getValueFor "angles" QVariant(QVariantMap, QMap(("dhuhrInterval", QVariant(int, 1) ) ( "fajrTwilightAngle" ,  QVariant(int, 18) ) ( "ishaInterval" ,  QVariant(int, 0) ) ( "ishaTwilightAngle" ,  QVariant(int, 18) ) ( "maghribInterval" ,  QVariant(int, 1) ) )  ) 
=== ../src/NotificationThread.cpp 48 timeout QDateTime("Tue Oct 14 00:05:03 2014") 
=== ../src/DataModelWrapper.cpp 48 calculate (QDateTime("Mon Oct 13 04:39:14 2014") ,  QDateTime("Mon Oct 13 05:49:59 2014") ,  QDateTime("Mon Oct 13 11:48:47 2014") ,  QDateTime("Mon Oct 13 15:08:39 2014") ,  QDateTime("Mon Oct 13 17:44:36 2014") ,  QDateTime("Mon Oct 13 18:54:20 2014") ,  QDateTime("Mon Oct 13 23:11:55 2014") ,  QDateTime("Tue Oct 14 01:01:01 2014") )  

looks like user changed the angles but still was 30 mins later.

**Comment by canadainc** [comment]
Issue was because of timezone was not being calculated properly (since integer round up was being used)

4581f8458cd25af71b9a8288e82c86cb7a738ed9
