### ISSUE TITLE
Empty points showing up on map

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#152]
```
Map is showing empty points
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 19 Nov 2014 at 7:18

Attachments:
* [1415764017464.zip](https://storage.googleapis.com/google-code-attachments/salat10/issue-152/comment-0/1415764017464.zip)

**Comment by canadainc** [comment]
c625547833bc6bb54aaebcc3c66b7d047665d56b
