### ISSUE TITLE
Egypt calculations seems to be wrong

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#157]
```
Investigate
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 14 Feb 2015 at 3:29

Attachments:
* [egypt.7z](https://storage.googleapis.com/google-code-attachments/salat10/issue-157/comment-0/egypt.7z)

**Comment by canadainc** [comment]
Duplicate of Implement Manual DST adjustment #146
