### ISSUE TITLE
Make the articles & quotes database as a plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/salat10#62]
```
Let the user download the database as a plugin to save app size
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 2 Mar 2014 at 4:10

**Comment by canadainc** [comment]
2796086366741475e035f2089adb772fd2e78f49

**Comment by canadainc** [comment]
Verified in GCR 4.2.0.0 with ClassicNA 10.3.2.2801
